local INFINI_ROOT = os.getenv("INFINI_ROOT") or (os.getenv(is_host("windows") and "HOMEPATH" or "HOME") .. "/.infini")

target("infinicore_infer")
    set_kind("shared")

    set_symbols("debug")
    add_includedirs("include", { public = false })
    add_includedirs(INFINI_ROOT.."/include", { public = true })

    add_linkdirs(INFINI_ROOT.."/lib")
    add_links("infiniop", "infinirt", "infiniccl")

    set_languages("cxx17")
    set_warnings("all", "error")

    add_files("src/models/*.cpp")
    add_files("src/models/*/*.cpp")
    add_files("src/tensor/*.cpp")
    add_files("src/allocator/*.cpp")
    add_files("src/dataloader/*.cpp")
    add_files("src/cache_manager/*.cpp")
    add_includedirs("include")

    set_installdir(INFINI_ROOT)
    add_installfiles("include/infinicore_infer.h", {prefixdir = "include"})
    add_installfiles("include/infinicore_infer/cache.h", {prefixdir = "include/infinicore_infer"})
    add_installfiles("include/infinicore_infer/kv_compression.h", {prefixdir = "include/infinicore_infer"})
    add_installfiles("include/infinicore_infer/weights_loader.h", {prefixdir = "include/infinicore_infer"})
    add_installfiles("include/infinicore_infer/models/*.h", {prefixdir = "include/infinicore_infer/models"})
target_end()

-- Simple test target for KV compression weight loading
target("test_kv_compression_load")
    set_kind("binary")
    add_files("tests/test_kv_compression_load.cpp")
    add_files("src/cache_manager/kv_compression.cpp", "src/cache_manager/kv_compression_impl.cpp", "src/cache_manager/kvcache.cpp")
    add_files("src/tensor/tensor.cpp", "src/tensor/strorage.cpp", "src/tensor/transform.cpp", "src/allocator/memory_allocator.cpp")
    add_files("src/models/inference_context.cpp")
    add_includedirs("include", "src", INFINI_ROOT.."/include")
    add_links("infiniop", "infinirt", "infiniccl")
    add_linkdirs(INFINI_ROOT.."/lib")
    set_languages("cxx17")
    set_warnings("all", "error")
    set_symbols("debug")
target_end()

-- Correctness test comparing compress output to dump_kv reference
target("test_kv_compression_correctness")
    set_kind("binary")
    add_files("tests/test_kv_compression_correctness.cpp")
    add_files("src/cache_manager/kv_compression.cpp", "src/cache_manager/kv_compression_impl.cpp", "src/cache_manager/kvcache.cpp")
    add_files("src/tensor/tensor.cpp", "src/tensor/strorage.cpp", "src/tensor/transform.cpp", "src/allocator/memory_allocator.cpp")
    add_files("src/models/inference_context.cpp")
    add_includedirs("include", "src", INFINI_ROOT.."/include")
    add_links("infiniop", "infinirt", "infiniccl")
    add_linkdirs(INFINI_ROOT.."/lib")
    set_languages("cxx17")
    set_warnings("all", "error")
    set_symbols("debug")
target_end()

-- Correctness test comparing against host reference
target("test_kv_compression_correctness")
    set_kind("binary")
    add_files("tests/test_kv_compression_correctness.cpp")
    add_files("src/cache_manager/kv_compression.cpp", "src/cache_manager/kv_compression_impl.cpp", "src/cache_manager/kvcache.cpp")
    add_files("src/tensor/tensor.cpp", "src/tensor/strorage.cpp", "src/tensor/transform.cpp", "src/allocator/memory_allocator.cpp")
    add_files("src/models/inference_context.cpp")
    add_includedirs("include", "src", INFINI_ROOT.."/include")
    add_links("infiniop", "infinirt", "infiniccl")
    add_linkdirs(INFINI_ROOT.."/lib")
    set_languages("cxx17")
    set_warnings("all", "error")
    set_symbols("debug")
target_end()
