#ifndef __TRIPLET_MARGIN_WITH_DISTANCE_LOSS_MOORE_API_H__
#define __TRIPLET_MARGIN_WITH_DISTANCE_LOSS_MOORE_API_H__

#include "../triplet_margin_with_distance_loss.h"

DESCRIPTOR(moore)

#endif // __TRIPLET_MARGIN_WITH_DISTANCE_LOSS_MOORE_API_H__
