#ifndef __INFINIOP_STATUS__
#define __INFINIOP_STATUS__

typedef enum {
    INFINIOP_STATUS_SUCCESS = 0,
    INFINIOP_STATUS_INTERNAL_ERROR = 1,
    INFINIOP_STATUS_BAD_PARAM = 2,
    INFINIOP_STATUS_BAD_TENSOR_DTYPE = 3,
    INFINIOP_STATUS_BAD_TENSOR_SHAPE = 4,
    INFINIOP_STATUS_BAD_TENSOR_STRIDES = 5,
    INFINIOP_STATUS_NULL_POINTER = 6,
    INFINIOP_STATUS_INSUFFICIENT_WORKSPACE = 7,
    INFINIOP_STATUS_DEVICE_TYPE_NOT_SUPPORTED = 8,
    INFINIOP_STATUS_BAD_DEVICE = 9,
    INFINIOP_STATUS_UNDEFINED_BEHAVIOR = 10,
} infiniopStatus_t;

#endif
