#pragma once

#include "op_type.hpp"

#include <cstdint>
#include <string>
#include <vector>

namespace infinicore::analyzer {

// ============================================================
// Phase & Bottleneck & Goal enumerations
// ============================================================

/// Recognized task phase types in LLM inference.
enum class PhaseType : uint8_t {
    UNKNOWN = 0,
    PREFILL,         // Long-sequence prefill phase
    DECODE,          // Autoregressive decode phase
    ATTENTION_DENSE, // Attention-dominated segment
    GEMM_MLP_DENSE,  // GEMM/MLP-dominated segment
    MOE_ROUTING,     // MoE routing segment (future)
    KV_CACHE,        // KV cache manipulation segment
    COMMUNICATION,   // Communication-dominated segment (future)
};

inline const char *phaseTypeToString(PhaseType phase) {
    switch (phase) {
    case PhaseType::PREFILL:
        return "prefill";
    case PhaseType::DECODE:
        return "decode";
    case PhaseType::ATTENTION_DENSE:
        return "attention_dense";
    case PhaseType::GEMM_MLP_DENSE:
        return "gemm_mlp_dense";
    case PhaseType::MOE_ROUTING:
        return "moe_routing";
    case PhaseType::KV_CACHE:
        return "kv_cache";
    case PhaseType::COMMUNICATION:
        return "communication";
    default:
        return "unknown";
    }
}

/// Primary bottleneck type of the current phase.
enum class BottleneckType : uint8_t {
    COMPUTE_BOUND = 0,
    MEMORY_BOUND,
    BANDWIDTH_BOUND,
    COMMUNICATION_BOUND,
    BALANCED,
};

inline const char *bottleneckTypeToString(BottleneckType bt) {
    switch (bt) {
    case BottleneckType::COMPUTE_BOUND:
        return "compute_bound";
    case BottleneckType::MEMORY_BOUND:
        return "memory_bound";
    case BottleneckType::BANDWIDTH_BOUND:
        return "bandwidth_bound";
    case BottleneckType::COMMUNICATION_BOUND:
        return "communication_bound";
    case BottleneckType::BALANCED:
        return "balanced";
    default:
        return "unknown";
    }
}

/// Optimization goal / objective preference.
enum class OptimizationGoal : uint8_t {
    LATENCY_FIRST = 0,
    THROUGHPUT_FIRST,
    MEMORY_SAFE,
    STABILITY_FIRST,
};

inline const char *optimizationGoalToString(OptimizationGoal goal) {
    switch (goal) {
    case OptimizationGoal::LATENCY_FIRST:
        return "latency_first";
    case OptimizationGoal::THROUGHPUT_FIRST:
        return "throughput_first";
    case OptimizationGoal::MEMORY_SAFE:
        return "memory_safe";
    case OptimizationGoal::STABILITY_FIRST:
        return "stability_first";
    default:
        return "unknown";
    }
}

// ============================================================
// Two-layer OptimizationIntent structure
//
// Design: Global Semantic Intent + Per-Device Local Refinement
// Rationale: Single-node multi-GPU scenario requires a unified
// task-level view PLUS per-device resource constraints.
// ============================================================

/// Strategy hints generated by the analyzer.
struct StrategyHint {
    bool prefer_fused_ops = false;     // Suggest op fusion?
    bool prefer_in_place = false;      // Suggest in-place computation?
    bool prefer_recomputation = false; // Suggest recompute to save memory?
    bool prefer_async_comm = false;    // Suggest async comm overlap?
};

/// Global semantic-level intent — describes the task's overall
/// compute characteristics and optimization direction.
struct GlobalSemanticIntent {
    // --- Current phase ---
    PhaseType current_phase = PhaseType::UNKNOWN;

    // --- Primary bottleneck ---
    BottleneckType primary_bottleneck = BottleneckType::BALANCED;

    // --- Optimization goal ---
    OptimizationGoal goal = OptimizationGoal::LATENCY_FIRST;

    // --- Compute intensity estimate (ops/byte) ---
    float compute_intensity = 0.0f;

    // --- Analysis confidence (0.0~1.0) ---
    float confidence = 0.0f;

    // --- Strategy hints ---
    StrategyHint strategy;

    // --- Production metadata ---
    uint64_t timestamp_ns = 0;
    uint32_t op_window_start = 0; // Start index of analyzed op window
    uint32_t op_window_end = 0;   // End index (exclusive) of analyzed op window
};

/// Per-device local intent — resource-aware refinement
/// for a specific device in multi-GPU scenario.
struct DeviceLocalIntent {
    int device_id = -1;

    // Memory utilization (0.0 ~ 1.0)
    float memory_usage_ratio = 0.0f;

    // Available memory in bytes
    size_t memory_available_bytes = 0;

    // Device-local bottleneck (may differ from global)
    BottleneckType local_bottleneck = BottleneckType::BALANCED;

    // Additional resource observations from the device snapshot
    float compute_utilization = 0.0f;
    float memory_bandwidth_utilization = 0.0f;
    float communication_time_ratio = 0.0f;

    // Confidence of the resource-side classification (0.0 ~ 1.0)
    float resource_confidence = 0.0f;
};

/// The complete OptimizationIntent: global task semantics
/// combined with per-device resource views.
///
/// Produced by: MutualAwarenessAnalyzer
/// Consumed by (roadmap):
///   1. MVP:    query/record/validation (Python + C++ API)
///   2. First:  OpDispatcher / kernel selection
///   3. Second: Allocator strategy (conservative vs aggressive)
///   4. Third:  Communication strategy (overlap, buffer, collective)
struct OptimizationIntent {
    GlobalSemanticIntent global;
    std::vector<DeviceLocalIntent> per_device;

    /// Get the local intent for a specific device, or nullptr if not found.
    const DeviceLocalIntent *getDeviceIntent(int device_id) const {
        for (auto &d : per_device) {
            if (d.device_id == device_id) {
                return &d;
            }
        }
        return nullptr;
    }
};

} // namespace infinicore::analyzer
