name: CI

on:
  pull_request:
    branches: ["main"]
    types: [opened, reopened, ready_for_review]
  workflow_dispatch:
    inputs:
      infinicore_branch:
        description: "InfiniCore Branch Name"
        required: false
        default: "main"
        type: string

jobs:
  ci:
    uses: InfiniTensor/ci/.github/workflows/infinilm-ci.yml@infiniCore_ci
    with:
      config_path: .github/ci_config.yaml
      ci_ref: infiniCore_ci
      infinicore_branch: ${{ github.event.inputs.infinicore_branch || 'main' }}
    secrets: inherit
